name: Trigger Jenkins Build and Fetch Artifacts

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Trigger Jenkins Build
        id: trigger
        run: |
          JENKINS_URL="http://54.92.26.219"
          JOB_PATH="/job/DDP_iOS/job/main"
          AUTH="${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"

          echo "📣 Triggering Jenkins build..."
          RESPONSE_HEADERS=$(mktemp)
          curl -X POST "$JENKINS_URL$JOB_PATH/buildWithParameters" \
            --user "$AUTH" \
            --header "Content-Type: application/json" \
            --data '{}' \
            -D $RESPONSE_HEADERS -o /dev/null

          QUEUE_URL=$(grep -Fi Location $RESPONSE_HEADERS | awk '{print $2}' | tr -d '\r\n')
          echo "✅ QUEUE_URL=$QUEUE_URL"
          echo "QUEUE_URL=$QUEUE_URL" >> $GITHUB_ENV

      - name: Get Jenkins Build URL
        run: |
          AUTH="${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"
          echo "⏳ Polling Jenkins queue for build number..."
          for i in {1..30}; do
            RESPONSE=$(curl -s -L "${QUEUE_URL}api/json" --user "$AUTH")
            BUILD_NUMBER=$(echo "$RESPONSE" | jq -r '.executable.number // empty')
            if [ -n "$BUILD_NUMBER" ]; then
              BUILD_URL="http://54.92.26.219/job/DDP_iOS/job/main/$BUILD_NUMBER/"
              echo "✅ BUILD_URL=$BUILD_URL"
              echo "BUILD_URL=$BUILD_URL" >> $GITHUB_ENV
              break
            fi
            sleep 5
          done

          if [ -z "$BUILD_NUMBER" ]; then
            echo "❌ Error: Jenkins build did not start in time."
            exit 1
          fi

      - name: Wait for Jenkins Build to Finish
        run: |
          AUTH="${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"
          echo "⏳ Waiting for Jenkins build to complete..."
          for i in {1..240}; do
            RESPONSE=$(curl -s -L "${BUILD_URL}api/json" --user "$AUTH")
            RESULT=$(echo "$RESPONSE" | jq -r '.result // empty')
            if [ "$RESULT" != "null" ] && [ -n "$RESULT" ]; then
              echo "✅ Build completed with result: $RESULT"
              echo "JENKINS_RESULT=$RESULT" >> $GITHUB_ENV
              if [ "$RESULT" == "SUCCESS" ]; then
                exit 0
              else
                exit 1
              fi
            fi
            sleep 10
          done

          echo "❌ Error: Jenkins build did not finish in time."
          exit 1

      - name: Download Artifacts from Jenkins
        if: env.JENKINS_RESULT == 'SUCCESS'
        run: |
          AUTH="${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"
          mkdir -p jenkins-artifacts

          echo "📦 Fetching list of artifacts..."
          ARTIFACTS_JSON=$(curl -s -L "${BUILD_URL}api/json" --user "$AUTH")
          echo "$ARTIFACTS_JSON" | jq -r '.artifacts[].relativePath' > artifact_paths.txt

          while IFS= read -r ARTIFACT_PATH; do
            if [[ "$ARTIFACT_PATH" == *"\$"* ]]; then
              echo "⚠️ Skipping unresolved path: $ARTIFACT_PATH"
              continue
            fi

            FILE_NAME=$(basename "$ARTIFACT_PATH")
            ARTIFACT_URL="${BUILD_URL}artifact/$ARTIFACT_PATH"
            echo "⬇️ Downloading: $ARTIFACT_URL"

            # Optional retry for flaky artifact availability
            for attempt in {1..3}; do
              curl -sf -O -J -L --user "$AUTH" "$ARTIFACT_URL" && break
              echo "⚠️ Retry $attempt failed. Retrying in 5s..."
              sleep 5
            done

            mv "$FILE_NAME" jenkins-artifacts/
          done < artifact_paths.txt

      - name: Upload Artifacts to GitHub
        if: env.JENKINS_RESULT == 'SUCCESS'
        uses: actions/upload-artifact@v4
        with:
          name: jenkins-artifacts
          path: jenkins-artifacts/
